language: ruby
rvm:
 - 2.6.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # JEKYLL_ENV=production

script:
 - bundle exec jekyll build

cache: bundler

deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET}
  skip_cleanup: true
  bucket: "sc-lib-ds-static"
  local_dir: _site
  upload_dir: nsarchive.swarthmore.edu
  detect_encoding: true
  default_text_charset: "utf-8"
branches:
    only:
        - master
notifications:
  email:
    - digitalscholarship@swarthmore.edu
  slack:
    secure: AetDr+I2gPTRJN5eOI1Hrbj+lvRtEc8L2ZdpfiOXAPveDhWxEYho46uxcu1YNskosEc/Hd4c5KR1YmIfj+YCxYwUuUmORkDnyzHxXhP+LBxDUwMs7i+kD+WabbJi1ws84llOlx21BjM2vrBZ1w4Z+RpP/G+VqbYCr7tI9xrTp0PbzmUbhemQUrEVD+UUBFdA7XTcWFPDYOyjBK9OHJS9xxEobxI4T6mxc3AZVBNLjLoQGjBqub8G/1xr/8aJXb8ZYceAijT8ellsqZIo70NOkZCLlCf8qGYTTdmNqKoaU6rsiPkguRAPQX0sekWZi7fqGfZEjtd6IK4+FnTIHxhg2xKAyauq16ZfhlEvVWxnYBZr/IoLyAEpuKVoSJbPZLWZ1pZjrJsbRaShPfrf33IadiMBDGBub9zpxpzSqKQwQyXPErS5qRX9CiNPABgyc1KKxKF4sBQRJ3AHBuiEy18uGVI12OvqBkPZHO4YRfiEIUKBMUXfXR8qnUR91aQJK6A7NK7yByPuBAUuwkHiU2ThkQysZlw3pmjTeD+On4YiKYzXmyuNUueCOV1Kqhy5NcCKiGoqTZ871YiujiTZuvOpJBZOdV3e1vfnvDVRmceFWwwbrbpKiOTVjBbfktdbQW5KaivElC4JurzhFPISPoKw3Ykydf0tJ+ju8t64JrVTT5U=