language: ruby
rvm:
 - 2.6.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # JEKYLL_ENV=production

script:
 - bundle exec jekyll build

cache: bundler

deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET}
  skip_cleanup: true
  bucket: "sc-lib-ds-static"
  local_dir: _site
  upload_dir: TARGET_FOLDER
  detect_encoding: true
  default_text_charset: "utf-8"
branches:
    only:
        - master
