# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            "National Security Archive Internship" 
tagline:          "coming soon...."
description:      "@ Swarthmore College"
url:              ""
baseurl:          /

author:
  name:           "Swarthmore College Libraries"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/swat-ds/nsarchive.swarthmore.edu

gems: [jekyll-paginate]

include: 
  - _pages
