# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            "NS Archive Internship @ Swarthmore College"
tagline:          'coming soon....'
description:      "Website for the National Security Archive Internship @ Swarthmore College"
url:              ""
baseurl:          /

author:
  name:           "Swarthmore College Libraries"


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]

include: 
  - _pages
